---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        com.example.myapp/prevent-start: "1"
    spec:
      containers:
        - name: my-app
          image: nginx
          command:
            - /bin/sh
            - -c
            - |
              for i in $(seq 1 10); do echo "INFO  - starting up $i"; sleep .1; done
              if [ -n "$PREVENT_START" ]; then echo 'ERROR - please disable metadata.annotations["com.example.myapp/prevent-start"]' to allow starting; fi
              for i in $(seq 11 60); do echo "INFO  - starting up $i"; sleep .1; done
              if [ -n "$PREVENT_START" ]; then echo 'ERROR - gonna crash now :+1: good luck figuring out why'; fi
              if [ -n "$PREVENT_START" ]; then exit 1; fi

              nginx -g 'daemon off;'
          env:
            - name: PREVENT_START
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['com.example.myapp/prevent-start']
          resources:
            requests:
              cpu: 128m
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - port: 80

