# temporary file to aid in reproduction of a problem
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: supportbundle-tutorial
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
  analyzers:
    - deploymentStatus:
        checkName: Deployment Status
        name: my-app
        namespace: default
        outcomes:
          - fail:
              when: "< 1"
              message: No ready replicas
          - pass:
              when: "= 1"
              message: At least one replica is ready
    - clusterPodStatuses:
        name: unhealthy
        namespaces:
          - default
        outcomes:
          - fail:
              when: "= Pending"
              message: 'Pod {{ .Name }} is unhealthy with a status of {{ .Status.Reason }}: {{ range .Status.Conditions }}{{.Reason}} -- {{.Message}}{{end}}'
          - fail:
              when: "!= Healthy"
              message: 'Pod {{ .Name }} is unhealthy with a status of {{ .Status.Reason }}'
